name: WPL Device Sync
version: 1.1.0
secure: no
  wallpaper:
    url: https://raw.githubusercontent.com/_/Wallpapers/San Francisco/sid-verma-k-LCaf7TOD8-unsplash.jpg
    position: fill
    photopea: yes
      colorize: yes 
      color: cyan
      saturation: 75
      brightness: 60
os: 
  version: Windows 10
user:
  github: 8rents